#dialect: org.hibernate.dialect.PostgreSQL82Dialect
#dialect: org.hibernate.dialect.Oracle10gDialect

hibernate:
  dialect: org.hibernate.dialect.Oracle10gDialect
  jdbc:
    batch_size: 10000
  order_inserts: true
  order_updates: true
  enable_lazy_load_no_trans: true
  show_sql: true
  format_sql: false
  id.new_generator_mappings: false


logging:
  level:
    com.antalex.db: debug
    org.hibernate.type:
      descriptor:
        sql.BasicBinder: INFO

spring:
  liquibase:
    enabled: false
  main:
    allow-circular-references: true

shardDbConfig:
  timeOut: 10
  liquibase:
    changeLogSrc: classpath:db/changelog
    changeLogName: db.changelog-master.yaml
  hikari:
    minimumIdle: 10
    maximumPoolSize: 20
  clusters:
    - name: MAIN
      defaultCluster: true
      shards:
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@localhost:1521/eks
            user: IBS
            pass: IBS
            owner: IBS
          id: 2
          hikari:
            minimumIdle: 20
            maximumPoolSize: 200
