hibernate:
  dialect: org.hibernate.dialect.Oracle10gDialect
  jdbc.batch_size: 10000
  order_inserts: true
  order_updates: true
  enable_lazy_load_no_trans: true
  show_sql: false
  format_sql: false
  id.new_generator_mappings: false

spring:
  liquibase:
      enabled: false
  datasource:
    hikari:
      minimumIdle: 20
      maximumPoolSize: 200

logging:
  level:
    org.hibernate.type:
      descriptor:
        sql.BasicBinder: INFO

test:
  prop: AAA
  name: BBB

dbConfig:
  clusters:
    - name: MAIN
      default: true
      shards:
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@localhost:1521/eks
            user: TEST
            pass: TEST
            owner: IBS
          main: true
          id: 2

