hibernate:
  dialect: org.hibernate.dialect.Oracle10gDialect
  jdbc.batch_size: 10000
  order_inserts: true
  order_updates: true
  enable_lazy_load_no_trans: true
  show_sql: false
  format_sql: false
  id.new_generator_mappings: false

spring:
  liquibase:
      enabled: false

logging:
  level:
    org.hibernate.type:
      descriptor:
        sql.BasicBinder: INFO

dbConfig:
  clusters:
    - name: MAIN
      default: true
      shards:
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@d5cftm-apc005ln.corp.dev.vtb:1521/ELVIS
            user: IBS
            pass: IBS
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@localhost:1521/eks
            user: IBS
            pass: IBS
          main: true
          id: 1
    - name: RAW
      id: 3
      shards:
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@d5ubss-or5001lk.corp.dev.vtb:1521/TARIFA
            user: IBS
            pass: IBS

