#dialect: org.hibernate.dialect.PostgreSQL82Dialect
#dialect: org.hibernate.dialect.Oracle10gDialect

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL82Dialect
  jdbc:
    batch_size: 1000000
  order_inserts: true
  order_updates: true
  enable_lazy_load_no_trans: true
  show_sql: false
  format_sql: false
  id.new_generator_mappings: false

logging:
  level:
    com.antalex.db: trace
    org.hibernate.type:
      descriptor:
        sql.BasicBinder: INFO

spring:
  liquibase:
    enabled: false

shardDbConfig:
  timeOut: 10
  sequenceCacheSize: 1000000
  TransactionConfig:
    activeConnectionParallelLimit: 12
    parallelCommit: true
  ThreadPool:
    corePoolSize: 10
    keepAliveTime: 60
    maximumPoolSize: 1000
  liquibase:
    changeLogSrc: classpath:db/changelog
    changeLogName: db.changelog-master.yaml
  hikari:
    minimumIdle: 3
    maximumPoolSize: 20
  clusters:
    - name: MAIN
      defaultCluster: true
      shards:
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@localhost:1521/eks
            user: TEST
            pass: TEST
            owner: IBS
          id: 2
          hikari:
            minimumIdle: 30
            maximumPoolSize: 200
          TransactionConfig:
            activeConnectionParallelLimit: 100
