hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  jdbc:
    batch_size: 1000000
  order_inserts: true
  order_updates: true
  enable_lazy_load_no_trans: true
  ddl-auto: update
  show_sql: false
  format_sql: false
  id.new_generator_mappings: true

shardDbConfig:
  processorTimeOut: 3600
  sequenceCacheSize: 1000000
  sqlInClauseLimit: 30
  #activeConnectionParallelLimit: 10
  percentActiveConnectionParallelLimit: 30
  parallelRun: true
  LockProcessor:
    timeOut: 10
    delay: 1
  ThreadPool:
    nameFormat: Multi-DB-%d
    corePoolSize: 10
    keepAliveTime: 60
    maximumPoolSize: 1000
  liquibase:
    changeLogSrc: classpath:db/changelog
    changeLogName: db.changelog-master.yaml
    enabled: true
  hikari:
    minimumIdle: 0
    maximumPoolSize: 20
    idleTimeout: 60
  checks:
    checkShardID: false
    checkClusterID: true
    checkClusterName: true
    checkMainShard: false
    checkClusterDefault: false
  clusters:
    - name: DEFAULT
      defaultCluster: true
      shards:
        - datasource:
            url: jdbc:postgresql://localhost:5432/main_1
            username: main_1
            password: main_1
        - datasource:
            url: jdbc:postgresql://localhost:5432/main_2
            username: main_2
            password: main_2
        - datasource:
            url: jdbc:postgresql://localhost:5432/main_3
            username: main_3
            password: main_3