#dialect: org.hibernate.dialect.PostgreSQL82Dialect
#dialect: org.hibernate.dialect.Oracle10gDialect

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL82Dialect
  jdbc:
    batch_size: 10000
  order_inserts: true
  order_updates: true
  enable_lazy_load_no_trans: true
  show_sql: false
  format_sql: false
  id.new_generator_mappings: false

logging:
  level:
    com.antalex.db: trace
    org.hibernate.type:
      descriptor:
        sql.BasicBinder: INFO

spring:
  liquibase:
    enabled: false

shardDbConfig:
  timeOut: 10
  sequenceCacheSize: 100000
  TransactionConfig:
    activeConnectionParallelLimit: 12
    parallelCommit: true
  ThreadPool:
    corePoolSize: 10
    keepAliveTime: 60
    maximumPoolSize: 1000
  liquibase:
    changeLogSrc: classpath:db/changelog
    changeLogName: db.changelog-master.yaml
  hikari:
    minimumIdle: 10
    maximumPoolSize: 20
  clusters:
    - name: MAIN
      defaultCluster: true
      shards:
        - database:
            url: ${PMTS_DATASOURCE_JDBC_URL_PUBLIC_1:jdbc:postgresql://d5pmts-pgc001lk.corp.dev.vtb:5432/pmts_public_1}
            user: ${PMTS_DB_PUBLIC_1_USER:pmts_public_1_admin}
            pass: ${PMTS_DB_PUBLIC_1_PASSWORD:123}
            owner: pmts_public_1
        - database:
            url: ${PMTS_DATASOURCE_JDBC_URL_PUBLIC_1:jdbc:postgresql://d5pmts-pgc001lk.corp.dev.vtb:5432/pmts_public_2}
            user: ${PMTS_DB_PUBLIC_2_USER:pmts_public_2_admin}
            pass: ${PMTS_DB_PUBLIC_2_PASSWORD:123}
            owner: pmts_public_2
        - database:
            url: ${PMTS_DATASOURCE_JDBC_URL_PUBLIC_1:jdbc:postgresql://d5pmts-pgc001lk.corp.dev.vtb:5432/pmts_main}
            user: ${PMTS_DB_MAIN_USER:pmts_main_admin}
            pass: ${PMTS_DB_MAIN_PASSWORD:123}
            owner: pmts_main
          main: true
          id: 63
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@d5cftm-apc005ln.corp.dev.vtb:1521/ELVIS
            user: IBS
            pass: IBS
          id: 1
        - id: 33
          url: https://test
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@localhost:1521/eks
            user: TEST
            pass: TEST
            owner: IBS
          id: 2
          hikari:
            minimumIdle: 30
            maximumPoolSize: 200
          TransactionConfig:
            activeConnectionParallelLimit: 100
    - name: RAW
      id: 1
      hikari:
        minimumIdle: 10
        maximumPoolSize: 20
      TransactionConfig:
        activeConnectionParallelLimit: 10
      shards:
        - database:
            driver: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@d5ubss-or5001lk.corp.dev.vtb:1521/TARIFA
            user: IBS
            pass: IBS
